name: Release
on: [push]
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Configure build toolchains
              shell: bash
              run: |
                if [ "${{ matrix.os }}" == "windows-latest" ]; then
                    echo "RS_TOOLCHAIN=stable-msvc" >> "$GITHUB_ENV"
                else 
                    echo "RS_TOOLCHAIN=stable" >> "$GITHUB_ENV"
                fi

            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: ${{ env.RS_TOOLCHAIN }}
                override: true

            - uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release

            - name: Determine artifact name
              shell: bash
              run: |
                echo "CARGO_NAME=$(cat Cargo.toml | tomlq -r ".bin[0].name")" >> "$GITHUB_ENV"
                echo "ARTIFACT_NAME=$(cat Cargo.toml | tomlq -r ".bin[0].name")-$(cat Cargo.toml | tomlq -r ".package.version")-$(./contrib/config.guess)" >> "$GITHUB_ENV"

            - uses: actions/upload-artifact@v3
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: target/release/${{ env.CARGO_NAME }}