name: Release
on: [push]
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Configure build toolchains
              shell: bash
              run: |
                if [ "${{ matrix.os }}" == "windows-latest" ]; then
                    echo "RS_TOOLCHAIN=stable-msvc" >> "$GITHUB_ENV"
                else 
                    echo "RS_TOOLCHAIN=stable" >> "$GITHUB_ENV"
                fi

            - name: Install dependencies
              shell: bash
              run: |
                pip install yq

            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: ${{ env.RS_TOOLCHAIN }}
                override: true

            - uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release

            - name: Determine artifact name
              shell: bash
              run: |
                CARGO_NAME=$(cat Cargo.toml | tomlq -r ".bin[0].name")
                CARGO_VERSION=$(cat Cargo.toml | tomlq -r ".package.version")
                echo "CARGO_NAME=$CARGO_NAME" >> "$GITHUB_ENV"
                echo "CARGO_VERSION=$CARGO_VERSION" >> "$GITHUB_ENV"
                ARTIFACT_NAME="$CARGO_NAME-$CARGO_VERSION-$(./contrib/config.guess)"
                
                echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"

                if [ "${{ matrix.os }}" == "windows-latest" ]; then
                    echo "ARTIFACT_UPLOADED_NAME=$ARTIFACT_NAME.exe" >> "$GITHUB_ENV"
                    echo "BIN_NAME=$CARGO_NAME.exe" >> "$GITHUB_ENV"
                else 
                    echo "ARTIFACT_UPLOADED_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"
                    echo "BIN_NAME=$CARGO_NAME" >> "$GITHUB_ENV"
                fi

            - uses: actions/upload-artifact@v3
              with:
                name: ${{ env.ARTIFACT_UPLOADED_NAME }}
                path: target/release/${{ env.BIN_NAME }}
        outputs:
            artifact_name: ${{ env.ARTIFACT_NAME }}
            version: ${{ env.CARGO_VERSION }}

    release:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        needs: [build]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Determine artifact name
              shell: bash
              run: |
                CARGO_NAME=$(cat Cargo.toml | tomlq -r ".bin[0].name")
                CARGO_VERSION=$(cat Cargo.toml | tomlq -r ".package.version")
                echo "CARGO_NAME=$CARGO_NAME" >> "$GITHUB_ENV"
                echo "CARGO_VERSION=$CARGO_VERSION" >> "$GITHUB_ENV"
                ARTIFACT_NAME="$CARGO_NAME-$CARGO_VERSION-$(./contrib/config.guess)"
                
                echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"

                if [ "${{ matrix.os }}" == "windows-latest" ]; then
                    echo "ARTIFACT_UPLOADED_NAME=$ARTIFACT_NAME.exe" >> "$GITHUB_ENV"
                else 
                    echo "ARTIFACT_UPLOADED_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"
                fi

            - uses: actions/download-artifact@v3
              with:
                name: ${{ env.ARTIFACT_UPLOADED_NAME }}

            - name: Get release details
              run: |
                echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
                echo "CURR_DATE=$(date +"%d/%m/%Y")" >> "$GITHUB_ENV"

            - name: Release
              id: release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ github.sha }}
                name: "Release ${{ env.CURR_DATE }} (${{ env.SHORT_SHA }})"
                body: "Build artifacts"
                artifacts: ${{ needs.build.outputs.artifact_name }}
                draft: true
        outputs:
            id: ${{ steps.release.outputs.id }}

    publish:
        needs: [release]
        runs-on: ubuntu-latest
        steps:
            - uses: eregon/publish-release@v1
              with:
                release_id: ${{ needs.release.outputs.id }}